# Generated by Django 4.1.4 on 2023-01-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeapp', '0003_remove_cashincategories_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='user',
        ),
        migrations.AlterField(
            model_name='balance',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContractorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
