# Generated by Django 4.1.4 on 2023-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_remove_contractor_user_alter_balance_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
