# Generated by Django 4.1.4 on 2023-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_alter_contractor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='description',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
