# Generated by Django 4.1.4 on 2023-01-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_alter_contractor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashin',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
